### ISSUE TITLE
Using ros-micro with humble

### ISSUE THREAD

**Issue by yoav26** [uhobeike/micro-ros-st-nucleo-f446re#16]
Hi, Got 2 error msg when trying to build:

3:29:33 **** Incremental Build of configuration Debug for project micro-ros-st-nucleo-f446re ****
make -j4 all 
docker pull microros/micro_ros_static_library_builder:galactic && docker run --rm -v /home/yoav/STM32CubeIDE/micro-ros-st-nucleo-f446re/Debug/../:/project --env MICROROS_LIBRARY_FOLDER=micro_ros_stm32cubemx_utils/microros_static_library_ide microros/micro_ros_static_library_builder:galactic
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=microros%2Fmicro_ros_static_library_builder&tag=galactic": dial unix /var/run/docker.sock: connect: permission denied
make[1]: *** [makefile:104: pre-build] Error 1
make: *** [makefile:77: all] Error 2
"make -j4 all" terminated with exit code 2. Build might be incomplete.

23:29:34 Build Failed. 2 errors, 0 warnings. (took 1s.255ms)

**Comment by uhobeike** [comment]
@yoav26 
Hello. 

In this package,
It is intended to run `docker` commands without `sudo`.

This is because it is tedious to type the command `sudo docker` every time.

Here is how to run docker commands without `sudo`.

```
sudo groupadd docker
sudo gpasswd -a $USER docker
sudo service docker restart
```

If you have any further questions, please ask.

**Comment by yoav26** [comment]
Hi, thanksI've got a build errors in the CubeIDE env. How it's connected to a dockers?I ran the above mentioned lines..In addition, if I have a local ROS distro, why do I need to use a docker?I think I'm missing something both in the PC side and in the microcontroller side.It will be great if you could explain some of this or refer me to another source.Maybe I should have ran the IDE from the same terminal session I ran the dockers?Thanks,Yoav
-------- Original message --------From: Tatsuhiro Ikebe ***@***.***> Date: 5/18/23  04:21  (GMT+02:00) To: uhobeike/micro-ros-st-nucleo-f446re ***@***.***> Cc: yoav26 ***@***.***>, Mention ***@***.***> Subject: Re: [uhobeike/micro-ros-st-nucleo-f446re] Using ros-micro with humble (Issue #16) 
@yoav26
Hello.
In this package,
It is intended to run docker commands without sudo.
This is because it is tedious to type the command sudo docker every time.
Here is how to run docker commands without sudo.
sudo groupadd docker
sudo gpasswd -a $USER docker
sudo service docker restart

If you have any further questions, please ask.

**Comment by uhobeike** [comment]
@yoav26
Have you tried this solution?
> @yoav26 Hello.
> 
> In this package, It is intended to run `docker` commands without `sudo`.
> 
> This is because it is tedious to type the command `sudo docker` every time.
> 
> Here is how to run docker commands without `sudo`.
> 
> ```
> sudo groupadd docker
> sudo gpasswd -a $USER docker
> sudo service docker restart
> ```
> 
> If you have any further questions, please ask.

**Comment by uhobeike** [comment]
Close for now due to lack of progress.

**Comment by yoav26** [comment]
Thank you for your email and sorry for the delay. I got caught up on
another project.
I'll check and get back to you, hope to get things running basics until the
end of next week.

Thanks,
Yoav
